package:
  name: plip
  version: "2.0.0"

source:
  git_rev: "recipe"
  git_url: https://github.com/pharmai/plip

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - openbabel
    - numpy
    - lxml
    - pymol

test:
  imports:
    - plip

about:
  home: https://github.com/ssalentin/plip
  license: GNU
  license_file: LICENSE.txt
