package:
  name: plip
  version: "1.4.2"

source:
  git_rev: "conda_plip"
  git_url: https://github.com/lkagami/plip.git
  
requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - openbabel
    - numpy
    - lxml
    - future
    - pymol

test:
  imports:
    - plip

about:
  home: https://github.com/ssalentin/plip
  license: GNU
  license_file: LICENSE.txt
