name: PLIP Docker Hub Depolyment

on:
  push

jobs:
  docker-hub:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Step
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pharmai/plip
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}]
